### ISSUE TITLE
Game design and related HTTP issues

### ISSUE THREAD

**Issue by possibly** [possibly/Applejax#4]
For reference, we currently have the idea of a Grid that contains objects. Two objects that occupy the Grid are Players and Trees. Tree's contain apples that can be obtained by the player, if the player is close enough. Players can trade/steal apples from other players in a close enough proximity in a Prisoner-Dilemma type deal. This is excellent and a great beginning to a game we could continually make more and more complex.

Currently @paulkass has mentioned a desire for the bots who play the game to have the ability to play in "real time." I think there would be issues with this since a Game State, or knowledges such as the whereabouts of players, whether a player can take a certain action, etc.,  must be maintained by the server. My main concern is that Game State could not be "pushed" to the requester due to the nature of HTTP. Game State would have to be requested by the player. This leads to another issue if we have a non-blocking IO since what the Game State pushed to Player X at time 0 will not be the same if they requested at time 2 if Player Y performed an action at time 1. Basically, old news is constantly being put out to the requesters of knowledge leading to impossible to resolve conflicts of "who did what first."

One solution I can think of is to have the server play in short-ish rounds, like a minute long each. Each registered player has one minute to make an action, and the server accepts your request and will make your move for you at the beginning of the next turn in the order it received it.  Each round presents itself as an opportunity for the requesters to request information, process it, and send their decisions back in.

Thoughts?

**Comment by paulkass** [comment]
I would like to have the client send it's information through GET or POST HTTP requests. So it would be optimal if the amount of information the client has to send would be minimal.

**Comment by possibly** [comment]
Well, the optimal amount of information is the amount of information needed to play the game. No getting around that.

Further research:
[HTTP vs. Websocket](http://gamedev.stackexchange.com/questions/38486/turn-based-game-http-or-websocket)
[Ajax Longpulling, Server push and Websocket](http://blogs.shephertz.com/2013/01/28/picking-the-right-communication-protocol-for-your-game/)
[Interesting pro's/cons' on SO](http://stackoverflow.com/a/1659702/3494646)

**Comment by paulkass** [comment]
Comet is an interesting possibility. Maybe we can create a separate branch later with the comet implementation.
@amixtum: what do you think?

**Comment by amixtum** [comment]
@paulkass 

Comet/long pulling and those other things could definitely work for your model of the game, where it is played by bots with a persistent connection, but there may be issues with it. For example, it is up to the "player", the programmer who writes the client in this case, to implement it properly, which is a dangerous assumption to make. What if I decide to write:

```
for i in range(100000):
    response = http.get("http://applejax/info")
    // do something with response
```

then I'm constantly opening and immediately closing TCP connections and wasting the server's resources. 

If we use Comet techniques, it may need to be under some API we write that ensures the client is connecting to server in a sane manner.

@possibly 

I was thinking of using a username/password approach to the problem. The premise is, the client has a unique hash that it sends to the server with its POST request (along with anything else). The server, upon setting up a session, assigns ID's to players, and sends them a hash (through some registration process?) allowing them to be sorted. The server's internal state, then, can contain information about what a client is _allowed_ to do at any given time, and whether they have received the most recent state of the game. It's extra book-keeping, but without too much cost.

**Comment by possibly** [comment]
@amixtum on long pulling

Excellent analysis.

Instead of writing our own API, we could use someone elses! I did a bit of googling and found a service called PubNub, which solves our issue quite nicely while [providing 70+ sdk's](http://www.pubnub.com/developers/) (thats 70+ different devices / languages supported! holy shit!). I found an example of a working long pull using [PubNub's library here](http://www.pubnub.com/developers/data-streams/hacker-news-articles) and it looks like exactly what we want while being so simple its beautiful. [Pricing is a not too bad...](http://www.pubnub.com/pricing/). If we got 15 people playing and enjoying our game, then I would pay the 15 bucks to allow 100 people to play.

@amixtum @paulkass 

I want to restate my problem more clearly after reading @amixtum's phrasing in the other thread: How do we communicate up to date Game State, fundamentally held by the server, to clients who can only request information?

@amixtum's suggestion can be extended to answer my main concern. Perhaps the server will do rounds, like in my suggestion, but instead of being a timed window of opportunity, the next round begins when the last client has been updated. (This is possible because the server keeps track of when the client has been updated last.) I like this idea more than my timed window of opportunity, and with PubNub is totally doable.

**Comment by paulkass** [comment]
@possibly What about afk'ers?

**Comment by possibly** [comment]
@paulkass robots go afk? 

I guess a robot could fail out. A mix of @amixtum's and my suggestion would be best then: timed window  + if everyone responds then a new round begins.

**Comment by paulkass** [comment]
So, because this issue was initially opened to decide whether we want a turn-base game or a real-time game, I will close this issue with my executive decision :). I will make a turn-based game with a 10 sec turn interval. Users will submit their actions which will be executed on a first-come, first-serve basis. Clients can interact only if they are one "square" away. The default action is `null` which means that the other person gets 2 apples no matter what the other person does. If they choose an action, then the bi-matrix that is described in `SoftwareOutline.txt` is implemented.
